### ISSUE TITLE
`Uncaught TypeError: Cannot read property 'appendChild' of null` with disabled status-bar

### ISSUE THREAD

**Issue by brumm** [sindresorhus/atom-editorconfig#178]
**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [editorconfig](https://github.com/sindresorhus/atom-editorconfig) package, v2.2.0

1. Disable statusbar package in settings
2. Open any file that will display a status-tile

### Stack Trace

```
Uncaught TypeError: Cannot read property 'appendChild' of null
At /Users/brumm/.atom/packages/editorconfig/lib/statustile-view.js:36
```

<details>
    <summary>Rest of stacktrace and stuff</summary>
    <p>
      ```
        TypeError: Cannot read property 'appendChild' of null
          at displayIcon (/Users/brumm/.atom/packages/editorconfig/lib/statustile-view.js:36:17)
          at Object.updateIcon (/Users/brumm/.atom/packages/editorconfig/lib/statustile-view.js:45:3)
          at setState (/Users/brumm/.atom/packages/editorconfig/index.js:19:15)
          at Object.applySettings (/Users/brumm/.atom/packages/editorconfig/index.js:104:5)
          at observeActivePaneItem (/Users/brumm/.atom/packages/editorconfig/index.js:239:36)
          at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
          at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
          at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:348:27
          at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
          at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
          at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:288:22)
          at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:420:19)
          at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:385:21)
          at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:570:16)
          at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:643:16)
          at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:623:12)
          at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:701:35)
          at Workspace.module.exports.Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:740:21)
          at atom-workspace.core:close (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:222:32)
          at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
          at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
          at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
          at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
          at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
          at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
        ```

        ### Commands

        ```
           -0:14.7.0 settings-view:open (input.hidden-input)
           -0:00.1.0 core:close (button.btn.icon.enablement.icon-playback-play)
        ```

        ### Config

        ```json
        {
        "core": {
          "customFileTypes": {
            "source.ini": [
              ".buckconfig",
              ".flowconfig"
            ],
            "source.json": [
              ".arcconfig"
            ],
            "source.python": [
              "BUCK"
            ]
          },
          "disabledPackages": [
            "deprecation-cop",
            "wrap-guide",
            "autoflow",
            "background-tips",
            "metrics",
            "atom-color-highlight",
            "jshint",
            "nuclide",
            "archive-view",
            "autosave",
            "welcome",
            "codenav",
            "linter-eslint",
            "status-bar"
          ],
          "ignoredNames": [
            "node_shrinkwrap",
            "node_modules",
            "bower_components",
            "cordova",
            ".DS_Store",
            ".git"
          ],
          "telemetryConsent": "limited",
          "themes": [
            "one-dark-ui",
            "base16-ocean-dark-syntax"
          ],
          "useCustomTitleBar": true
        }
        }
        ```

        ### Installed Packages

        ```coffee
        # User
        advanced-open-file, v0.16.5 (inactive)
        api-docs, v0.0.6 (active)
        atom-beautify, v0.29.17 (inactive)
        atom-material-syntax, v1.0.2 (inactive)
        base16-ocean-dark-syntax, v1.0.1 (active)
        click-link, v1.0.10 (active)
        clipboard-plus, v0.5.1 (active)
        codenav, v0.0.0 (inactive)
        color-picker, v2.2.4 (active)
        duplicate-line-or-selection, v0.9.0 (inactive)
        editorconfig, v2.2.0 (active)
        emmet, v2.4.3 (active)
        expand-selection-to-quotes, v0.11.0 (inactive)
        file-icons, v2.0.13 (active)
        git-blame, v0.4.11 (inactive)
        highlight-bad-chars, v1.0.5 (active)
        highlight-selected, v0.12.0 (active)
        image-view, v0.60.0 (active)
        indent-helper, v0.2.0 (inactive)
        language-babel, v2.51.0 (active)
        last-tab, v0.1.6 (inactive)
        linter, v1.11.21 (active)
        linter-eslint, v8.1.0 (inactive)
        merge-conflicts, v1.4.4 (active)
        narrow, v0.15.0 (active)
        oceanic-next, v1.0.0 (inactive)
        one-dark-ui, v1.9.0 (active)
        pigments, v0.39.0 (active)
        require2import, v1.2.0 (inactive)
        set-syntax, v0.3.2 (active)
        sort-lines, v0.14.0 (inactive)
        split-selection-into-cursors, v0.2.0 (inactive)
        swap-selection, v0.4.0 (inactive)
        tidy-tabs, v0.3.0 (active)
        atom-dark-syntax, v0.28.0 (inactive)
        atom-dark-ui, v0.53.0 (inactive)
        atom-light-syntax, v0.29.0 (inactive)
        atom-light-ui, v0.46.0 (inactive)
        base16-tomorrow-dark-theme, v1.4.0 (inactive)
        base16-tomorrow-light-theme, v1.4.0 (inactive)
        one-dark-ui, v1.9.0 (active)
        one-light-ui, v1.8.2 (inactive)
        one-dark-syntax, v1.6.0 (inactive)
        one-light-syntax, v1.6.0 (inactive)
        solarized-dark-syntax, v1.1.1 (inactive)
        solarized-light-syntax, v1.1.1 (inactive)
        about, v1.7.2 (active)
        archive-view, v0.62.0 (inactive)
        autocomplete-atom-api, v0.10.0 (active)
        autocomplete-css, v0.14.1 (active)
        autocomplete-html, v0.7.2 (active)
        autocomplete-plus, v2.33.1 (active)
        autocomplete-snippets, v1.11.0 (active)
        autoflow, v0.29.0 (inactive)
        autosave, v0.23.2 (inactive)
        background-tips, v0.26.1 (inactive)
        bookmarks, v0.43.2 (active)
        bracket-matcher, v0.85.1 (active)
        command-palette, v0.39.1 (inactive)
        deprecation-cop, v0.55.1 (inactive)
        dev-live-reload, v0.47.0 (active)
        encoding-selector, v0.22.0 (active)
        exception-reporting, v0.40.0 (active)
        find-and-replace, v0.204.5 (inactive)
        fuzzy-finder, v1.4.0 (active)
        git-diff, v1.2.0 (active)
        go-to-line, v0.31.2 (inactive)
        grammar-selector, v0.48.2 (active)
        image-view, v0.60.0 (active)
        incompatible-packages, v0.26.1 (active)
        keybinding-resolver, v0.35.0 (active)
        line-ending-selector, v0.5.1 (active)
        link, v0.31.2 (inactive)
        markdown-preview, v0.159.3 (active)
        metrics, v1.1.3 (inactive)
        notifications, v0.65.1 (active)
        open-on-github, v1.2.1 (inactive)
        package-generator, v1.0.2 (inactive)
        settings-view, v0.244.0 (active)
        snippets, v1.0.4 (active)
        spell-check, v0.68.5 (active)
        status-bar, v1.6.0 (inactive)
        styleguide, v0.48.0 (active)
        symbols-view, v0.113.1 (inactive)
        tabs, v0.103.1 (active)
        timecop, v0.33.2 (active)
        tree-view, v0.211.1 (active)
        update-package-dependencies, v0.10.0 (active)
        welcome, v0.35.1 (inactive)
        whitespace, v0.35.0 (active)
        wrap-guide, v0.39.0 (inactive)
        language-c, v0.54.0 (active)
        language-clojure, v0.22.1 (active)
        language-coffee-script, v0.48.1 (active)
        language-csharp, v0.13.0 (active)
        language-css, v0.40.1 (active)
        language-gfm, v0.88.0 (active)
        language-git, v0.15.0 (active)
        language-go, v0.43.0 (active)
        language-html, v0.47.1 (active)
        language-hyperlink, v0.16.1 (active)
        language-java, v0.24.0 (active)
        language-javascript, v0.122.0 (active)
        language-json, v0.18.3 (active)
        language-less, v0.29.6 (active)
        language-make, v0.22.2 (active)
        language-mustache, v0.13.0 (active)
        language-objective-c, v0.15.1 (active)
        language-perl, v0.37.0 (active)
        language-php, v0.37.3 (active)
        language-property-list, v0.8.0 (active)
        language-python, v0.45.1 (active)
        language-ruby, v0.70.2 (active)
        language-ruby-on-rails, v0.25.1 (active)
        language-sass, v0.57.0 (active)
        language-shellscript, v0.23.0 (active)
        language-source, v0.9.0 (active)
        language-sql, v0.25.0 (active)
        language-text, v0.7.1 (active)
        language-todo, v0.29.1 (active)
        language-toml, v0.18.1 (active)
        language-xml, v0.34.12 (active)
        language-yaml, v0.27.1 (active)

        # Dev
        No dev packages
      ```
    </p>
</details>

**Comment by florianb** [comment]
Hi @brumm - thanks for the report, i won't have the time to debug this in the next week. I beg for patience.. 😄

**Comment by brumm** [comment]
No problem, I went ahead and fixed it myself: https://github.com/sindresorhus/atom-editorconfig/pull/180

**Comment by florianb** [comment]
Thank you very much for your support @brumm. I guess it will land soon! 👍 🍰

**Comment by balupton** [comment]
in the meantime we can do:

```
apm uninstall editorconfig
apm install brumm/atom-editorconfig
```
