### ISSUE TITLE
Uncaught TypeError: editor.update is not a function

### ISSUE THREAD

**Issue by ednilsonamaral** [sindresorhus/atom-editorconfig#179]
I have that error when using this plugin.

I need to disabled the atom-editorconfig or I can't work with Atom.

Any solution for this issue?

**Atom Version**: 1.8.0
**System**: Debian GNU/Linux
**Thrown From**: [editorconfig](https://github.com/sindresorhus/atom-editorconfig) package, v2.0.5

### Stack Trace

Uncaught TypeError: editor.update is not a function

```
At /home/ednilson/.atom/packages/editorconfig/index.js:169

TypeError: editor.update is not a function
    at Object.applySettings (/home/ednilson/.atom/packages/editorconfig/index.js:169:13)
    at observeActivePaneItem (/home/ednilson/.atom/packages/editorconfig/index.js:322:36)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:282:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/usr/share/atom/resources/app.asar/src/pane.js:414:19)
    at Pane.module.exports.Pane.activatePreviousItem (/usr/share/atom/resources/app.asar/src/pane.js:379:21)
    at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app.asar/src/pane.js:564:16)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:637:16)
    at atom-tabs.TabBarView.onClick (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:688:17)
```

**Comment by florianb** [comment]
@ednilsonamaral thanks for reporting the issue.

Please provide
- [ ] a list of your currently active packages

I won't be able to dig into this in the next week. I beg for patience.

**Comment by rolandjitsu** [comment]
I've actually got not additional packages, just this one. But I use an old version of Atom, actually Particle Dev which uses Atom.

**Comment by ednilsonamaral** [comment]
@florianb 

- Stylus (matthojo);  
- autocomplete-ionic-framework (chrisgriffith);  
- emmet;  
- file-icons (DanBrooker);  
- fonts (braver);  
- ionic-preview (cabaag);  
- language-pug (genoma);  
- language-vue (hedefalk);  
- linter;  
- linter-eslint;  
- minimap;  
- pigments;  
- vue-format (LeslieYQ);  
- vue-snippets (ealves-pt);  
- editorconfig.

**Comment by florianb** [comment]
@rolandjitsu - i am sorry i can't support Particle Dev. And i currently don't know an elegant way to support older versions of Atom properly, since there where breaking changes introduced to the UI (by [removing the shadow dom](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html)).

If you'd like to address issues related to Particle Dev please open a new issue for that.

**Comment by florianb** [comment]
@ednilsonamaral i am really sorry, we have a broken engine-dependency in that release, version 2.0.5 of atom-editorconfig is not compatible with atom < 1.11.x.

Since Atom has introduced breaking ui-changes with 1.13 and i don't know an elegant way to support two versions of Atom (before 1.13 and latest), i can't think of an easy fix.

I guess updating to the latest Atom is on option?

I will have to think about this.

**Comment by ednilsonamaral** [comment]
@florianb now I use the Atom v. 1.14.1. For now, editorconfig it's working! Any new issues I notify you here..

tks ;)

**Comment by florianb** [comment]
@ednilsonamaral happy to hear that! Happy coding! 😄 ☕️
