### ISSUE TITLE
New Win7 install: Failed to load the editorconfig package

### ISSUE THREAD

**Issue by tomByrer** [sindresorhus/atom-editorconfig#37]
Win7_64, installing v0.208.0 via zip, v0.209.0 via AtomSetup.exe, got same error both times.

---
Failed to load the editorconfig package
Cannot find module 'emissary'

Hide Stack Trace
Error: Cannot find module 'emissary'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\t\AppData\Local\atom\app-0.209.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\t\.atom\packages\editorconfig\index.js:2:18)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (C:\Users\t\AppData\Local\atom\app-0.209.0\resources\app.asar\src\babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)

---
Figured since this is the only package in the new installs I have issues with, I'd post here.  Let me know if I should punt to atom/atom.

**Comment by sindresorhus** [comment]
Installs fine for me. Atom issue, or would rather guess a network issue on your part.

**Comment by batjko** [comment]
Well, if emissary can't be found by your package, and Atom otherwise works fine, it would indeed point to this package as an issue. 
Perhaps a combination of configurations?

In any event (pardon the pun), Atom is moving away from emissary, towards event-kit. Might be an idea to switch at some point.

**Comment by tomByrer** [comment]
I think I had this package left over from an old install.
I'm doing more testing...

**Comment by LionelPaulus** [comment]
Hi,

I've got this error each time I open a new project: **Cannot find module 'pify'**

**Comment by florianb** [comment]
Hi @LionelPaulus, thanks for getting in touch.

1. Please try to reinstall the editorconfig-package (f.e. with `$ apm install editoroconfig`)
2. Open a new issue with **all** necessary information so we can dig deeper into it.

> 📢  **Whoever lands here:** Please open a new issue - i lock this conversation since `Failed to load the editorconfig package` is a collective topic which is not meaningful and makes this thread unmanageable.
