### ISSUE TITLE
Uncaught Error: Cannot find module 'jshint/src/cli'

### ISSUE THREAD

**Issue by cstipkovic** [sindresorhus/atom-editorconfig#99]
[Enter steps to reproduce below:]

1. Install Atom
2. Install atom-editorconfig package via apm
3. Open Atom via command-line

**Atom Version**: 1.9.8
**System**: Linux Mint
**Thrown From**: [editorconfig](https://github.com/sindresorhus/atom-editorconfig) package, v1.4.1

### Stack Trace

Uncaught Error: Cannot find module 'jshint/src/cli'

```
At module.js:341

Error: Cannot find module 'jshint/src/cli'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at lazy (/home/cin_chalic/.atom/packages/editorconfig/node_modules/lazy-req/index.js:34:36)
    at /home/cin_chalic/.atom/packages/editorconfig/node_modules/lazy-req/index.js:8:11
    at lint (/home/cin_chalic/.atom/packages/jshint/index.js:232:14)
    at complete (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
    at delayed (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7707:11)
```

### Commands

```
     -0:00.6.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "fileEncoding": "iso885910"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.5 (active)
angularjs-snippets, v0.10.18 (active)
atom-bootstrap3, v1.2.12 (inactive)
atom-jasmine, v0.8.1 (active)
atom-jshint, v2.0.0 (active)
atom-ternjs, v0.14.2 (active)
auto-indent, v0.5.0 (active)
autoclose-html, v0.23.0 (active)
autocomplete-clang, v0.9.4 (active)
editorconfig, v1.4.1 (active)
emmet, v2.4.3 (active)
es6-javascript, v1.0.0 (inactive)
file-type-icons, v1.3.2 (active)
format-sql, v0.3.0 (inactive)
html-entities, v0.4.0 (active)
indentation-indicator, v1.0.0 (active)
javascript-snippets, v1.2.1 (active)
jshint, v1.8.5 (active)
language-latex, v0.6.1 (active)
language-velocity, v0.1.2 (active)
latex, v0.35.0 (inactive)
latexer, v0.3.0 (active)
linter, v1.11.16 (active)
linter-clang, v3.4.4 (active)
linter-jscs, v4.0.5 (active)
minimap, v4.24.7 (active)
opened-files, v0.3.6 (active)
pain-split, v1.4.0 (active)
reveal-active-file-context, v0.2.0 (active)
todo-show, v1.7.0 (inactive)
trailing-spaces, v0.3.2 (active)
turbo-javascript, v1.4.0 (inactive)
wakatime, v6.0.10 (active)
Zen, v0.16.4 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by cstipkovic** [comment]
Sorry about that, I did not read the REAME file about deprecated package.

"Deprecated

I failed to find an active maintainer. See linter-jshint for an alternative. However, I would strongly recommend trying out ESLint (Atom plugin) instead. It's just so much better than JSHint. XO (Atom plugin), which is an ESLint wrapper with sensible defaults, is also a good choice."
